### ISSUE TITLE
User wants to Login

### ISSUE THREAD

**Issue by ethragur** [ethragur/SMRTMS#1]
Simple login window
In android (no func)
Ideas about login. User storage. Technology choices
4 hours

**Comment by HunterwolfAT** [comment]
##Basic Overview
Login data needs to be saved and verified by the server, not the client software.
The client needs the option to save the most recently used username **(not password!)**.

Since the app allows to track other users and be tracked by them, saving the password on the client should not be an option, in case somebody gets a hold of somebody elses phone, for example.

##Technology
For User verification, a simple database on the server, with the users email address and hashed password, should be enough. The client sends the entered password to the server, where the input gets hashed and checked against the stored hashed password. If they match, the server sends a OK-signal to the client.

To archive this, any kind of database on the server will be sufficient. The communication could be archieved via standard methods that Java provides to connect with a database.

**Comment by HunterwolfAT** [comment]
Alternatively, we could use a authentication API like [Google+] (https://developers.google.com/+/) or [Twitter] (https://dev.twitter.com/twitter-kit/android/twitter-login)!
